"""added updated field to course

Revision ID: 51668c2ee252
Revises: b670e825b4e8
Create Date: 2021-12-19 15:48:52.137118

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51668c2ee252'
down_revision = 'b670e825b4e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('date_updated', sa.Date(), nullable=True))
    op.create_index(op.f('ix_courses_date_updated'), 'courses', ['date_updated'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_courses_date_updated'), table_name='courses')
    op.drop_column('courses', 'date_updated')
    # ### end Alembic commands ###
