"""Added "date_enrolled" column to registrations table

Revision ID: 80d9145e97e5
Revises: be2652ab211a
Create Date: 2021-12-08 18:46:29.971620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80d9145e97e5'
down_revision = 'be2652ab211a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user-course', sa.Column('date_enrolled', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user-course', 'date_enrolled')
    # ### end Alembic commands ###
