"""Added small_desc column to Course model

Revision ID: 8fe1e1128029
Revises: cd1380da0fa2
Create Date: 2021-12-04 22:35:00.937523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fe1e1128029'
down_revision = 'cd1380da0fa2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('small_desc', sa.Text(length=150), nullable=True))
    op.add_column('courses', sa.Column('date_created', sa.Date(), nullable=True))
    op.add_column('courses', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_courses_date_created'), 'courses', ['date_created'], unique=False)
    op.create_foreign_key(None, 'courses', 'users', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='foreignkey')
    op.drop_index(op.f('ix_courses_date_created'), table_name='courses')
    op.drop_column('courses', 'author_id')
    op.drop_column('courses', 'date_created')
    op.drop_column('courses', 'small_desc')
    # ### end Alembic commands ###
