"""Slightly changed User model

Revision ID: cd1380da0fa2
Revises: 785b93395635
Create Date: 2021-12-02 16:17:30.743213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd1380da0fa2'
down_revision = '785b93395635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'courses', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'courses', type_='unique')
    # ### end Alembic commands ###
