version: '3.8'

services:
  web:
    image: flask_app_gunicorn
    build: ./
    command: gunicorn --bind 0.0.0.0:5000 -w 3 run:app
    container_name: flask-app
    volumes:
      - ./:/usr/src/flask_app/
    networks:
      - flask_network
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: pg-db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: flask-dev
    ports:
      - 5432:5432
    networks:
      - flask_network

volumes:
  pg_data:
    external: true
    name: pg_data
  
networks:
  flask_network: