version: '3.8'

services:
  web:
    image: flask_app_v3
    build: ./
    command: python run.py
    container_name: flask_app
    volumes:
      - ./:/usr/src/flask_app/
    ports:
      - 5000:5000
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    restart: always
    container_name: pg-db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: flask-dev
    ports:
      - 5432:5432

volumes:
  pg_data:
    external: true
    name: pg_data