version: '3.8'

services:
  db:
    image: postgres
    restart: always
    container_name: pg-db
    volumes:
      - pg_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: pass123
      POSTGRES_DB: flask-dev
    ports:
      - '5432:5432'
    
volumes:
  pg_data:
    # external: true